### ISSUE TITLE
Authenticating with unknown user or wrong password yields unclear error message

### ISSUE THREAD

**Issue by mrotteveel** [nakagami/pyfirebirdsql#75]
Authenticating with an unknown user yields an unclear error message _TypeError: a bytes-like object is required, not 'NoneType'_ instead of the Firebird error _"Your user name and password are not defined. Ask your database administrator to set up a Firebird login."_

For example 

```
import firebirdsql

con = firebirdsql.connect(
    host='localhost', database='employee',
    user='doesnotexist', password='password'
  )
```

Yields

```
Traceback (most recent call last):
  File "simpleconnect.py", line 5, in <module>
    user='doesnotexist', password='password'
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\__init__.py", line 96, in connect
    return Connection(**kwargs)
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\fbcore.py", line 615, in __init__
    self._op_accept()
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\wireprotocol.py", line 534, in _op_accept
    p.pack_string(bytes_to_hex(auth_data))
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\utils.py", line 57, in bytes_to_hex
    s = binascii.b2a_hex(b)
TypeError: a bytes-like object is required, not 'NoneType'
```
In a similar vein, authenticating with the wrong password yields an error _"firebirdsql.InternalError: InternalError"_ instead of the Firebird error _"Your user name and password are not defined. Ask your database administrator to set up a Firebird login."_:

```
import firebirdsql

con = firebirdsql.connect(
    host='localhost', database='employee',
    user='sysdba', password='wrongpassword'
  )
```
Yields:

```
Traceback (most recent call last):
  File "simpleconnect.py", line 5, in <module>
    user='sysdba', password='wrongpassword'
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\__init__.py", line 96, in connect
    return Connection(**kwargs)
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\fbcore.py", line 615, in __init__
    self._op_accept()
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\wireprotocol.py", line 539, in _op_accept
    (h, oid, buf) = self._op_response()
  File "C:\DevSoft\python\python-3.6.1\lib\site-packages\firebirdsql\wireprotocol.py", line 990, in _op_response
    raise InternalError
firebirdsql.InternalError: InternalError
```

Python 3.6.4
pyfirebirdsql: 1.1.0

**Comment by nakagami** [comment]
First issue fixed.

InternalError is still occurring.

**Comment by nakagami** [comment]
raise OperationalError instead of InternalError
