### ISSUE TITLE
fbcore error in event_conduit with firebird 3.0.4 

### ISSUE THREAD

**Issue by intellekta** [nakagami/pyfirebirdsql#78]
system
```
Windows server 2012.r2x64 - fb 3.0.4
Windows client w10x64 - fb 3.0.4 - py 3.7.1 32bit - fbcore.py 1.1.1 - 2.0
```

error

```
Traceback (most recent call last):
  File "H:\_Python\Python\IXS_M2S\fb-test.py", line 150, in doEvent
    conduit = conn.event_conduit(aEvent)
  File "C:\Python37\lib\site-packages\firebirdsql\fbcore.py", line 806, in event_conduit
    return EventConduit(self, event_names, timeout)
  File "C:\Python37\lib\site-packages\firebirdsql\fbcore.py", line 490, in __init__
   self.sock = SocketStream(ip_address, port, timeout)
UnboundLocalError: local variable 'ip_address' referenced before assignment
```

i put some printing in the code between line 485 and 489 with these results

```
buffer    : b'1700c8d60000000000000000000000000000ffffc0a8025100000000'
family    : b'1700'
port      : 51495
```

and here is the code:

```python
476         if family == b'\x02\x00':     # IPv4
477            ip_address = '.'.join([str(byte_to_int(c)) for c in buf[4:8]])
478        elif family == b'\x0a\x00':  # IPv6
479            address = bytes_to_hex(buf[8:24])
480            if not isinstance(address, str):    # Py3
481                address = address.decode('ascii')
482            ip_address = ':'.join(
483                [address[i: i+4] for i in range(0, len(address), 4)]
484            )
485        ## family == b'\x17\x00':     2018.11.30.uc - unknown IP family ???
486        print('buffer    : ' + str(bytes_to_hex(buf )))
487        print('family    : ' + str(bytes_to_hex(family )))
488        print('port      : ' + str(port))
489        ## family == b'\x17\x00':     2018.11.30.uc - unknown IP family ???
490        self.sock = SocketStream(ip_address, port, timeout)
```

**Comment by nakagami** [comment]
Sorry, I think it's probably fixed, so I'll close it.
