### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 5: invalid continuation byte

### ISSUE THREAD

**Issue by greenfield-br** [nakagami/pyfirebirdsql#97]
Hello.

the following code

```
import firebirdsql

#con = fdb.connect(dsn='/home/operations/dev/HLT.FDB', user='sysdba', password='masterkey')

conn = firebirdsql.connect(
    host='localhost',
    database='HLT',
    port=3050,
    user='SYSDBA',
    password='masterkey'
)

#SQLX = "SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='FECHAMENTO_CAIXA';"
SQLX = "SELECT * FROM FECHAMENTO_CAIXA;"
cur = conn.cursor()
cur.execute(SQLX)
response_tables = cur.fetchall()

print(response_tables)

conn.close()

```

gives the following error

```
Traceback (most recent call last):
  File "table.py", line 15, in <module>
    response_tables = cur.fetchall()
  File "/home/operations/.local/lib/python3.6/site-packages/firebirdsql/fbcore.py", line 392, in fetchall
    return [tuple(r) for r in self._fetch_records]
  File "/home/operations/.local/lib/python3.6/site-packages/firebirdsql/fbcore.py", line 392, in <listcomp>
    return [tuple(r) for r in self._fetch_records]
  File "/home/operations/.local/lib/python3.6/site-packages/firebirdsql/fbcore.py", line 228, in _fetch_generator
    (rows, more_data) = connection._op_fetch_response(stmt.handle, stmt.xsqlda)
  File "/home/operations/.local/lib/python3.6/site-packages/firebirdsql/wireprotocol.py", line 1002, in _op_fetch_response
    r[i] = x.value(raw_value)
  File "/home/operations/.local/lib/python3.6/site-packages/firebirdsql/xsqlvar.py", line 159, in value
    return self.bytes_to_str(raw_value)
  File "/home/operations/.local/lib/python3.6/site-packages/firebirdsql/wireprotocol.py", line 251, in bytes_to_str
    return b.decode(charset_map.get(self.charset, self.charset))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 5: invalid continuation byte

```

however, if SQLX is defined according to the commented line, instead, then it works.
what am i doing wrong, please?
my best guess is that i need to set chartset in the connect method, however i am not sure what do do.

any help is much appreciated.
best regards.

**Comment by greenfield-br** [comment]
hi. this solves it.

```
conn = firebirdsql.connect(
    host='localhost',
    database='HLT',
    port=3050,
    user='SYSDBA',
    password='masterkey',
    charset='ISO8859_1')

```
